#! /bin/bash
# Convenience script for users of Mount Sinai's demeter cluster.
# Executes the most recently modified guacamole jar with arguments for running on demeter.
#
# Example invocation:
#
# scripts/guacamole-demeter threshold \
# 	-reads hdfs://demeter-nn1/user/ahujaa01/ftp-trace.ncbi.nih.gov/1000genomes/ftp/data/HG00096/alignment/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam \
#	 -out hdfs://demeter-nn1/user/odonnt02/threshold.gt.adam
#
set -e
set -x
export SPARK_MEM=6G
export SPARK_JAVA_OPTS="-Dspark.default.parallelism=2 -Dspark.shuffle.consolidateFiles=true -Dspark.speculation=true"
jar=$(ls -tc guacamole-core/target/guacamole-?.*.jar | head -n 1)
jar_abs=$(pwd)/$jar
exec time java -Xmx8g -XX:MaxPermSize=4g $SPARK_JAVA_OPTS -jar $jar_abs \
	"$@" \
	-spark_master spark://demeter-mgmt1.demeter.hpc.mssm.edu:7077 \
	-spark_jar $jar_abs

